# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = waybar
exec-once = mako
exec-once = hypridle
exec-once = notarchy-wallpaper current
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
