windowrule = float on, match:class ^org\.notarchy\.(bluetui|impala|wiremix)$
windowrule = center on, match:class ^org\.notarchy\.(bluetui|impala|wiremix)$
windowrule = size 875 600, match:class ^org\.notarchy\.(bluetui|impala|wiremix)$
