force_keyboard_focus = true                                                 # forces keyboard forcus to stay in Walker
selection_wrap = true                                                       # wrap list if at bottom or top
theme = "notliad"                                                   # theme to use
additional_theme_location = "~/.config/walker/themes/"
hide_action_hints = false                                                   # show available actions to new users

[placeholders]
"default" = { input = " Search apps, files, or the web...", list = "No matches. Try another name or a provider prefix." }

[keybinds]
quick_activate = []

[columns]
symbols = 1 # providers to be queried by default

[providers]
max_results = 64
default = [
  "desktopapplications",
  "websearch",
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"

[[providers.prefixes]]
prefix = "$"
provider = "clipboard"

[[emergencies]]
text = "Restart Walker"
command = "pkill walker; walker"
